---
title: "Report_05_01"
author: "Maria Paula Fuentes, Deniz Korkmazel, Evgeniya Abadzhieva, Hanna Frieß"
date: "2023-07-08"
output: pdf_document
toc: true
---

```{=tex}
\begin{center}
Ruprecht-Karls-University of Heidelberg  Faculty of Engineering Science  B.Sc. Molecular Biotechnology
\end{center}
```
\tableofcontents

```{r  globalenv = TRUE}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism_gastric_cleaned_treatments <- prism_gastric[, colSums(is.na(prism_gastric)) == 0]


prism_gastric_cleaned_treatments_t<- t(prism_gastric_cleaned_treatments)
pca_result_gastric_cleaned_treatments_t<- prcomp(prism_gastric_cleaned_treatments_t)
pca_values_gastric_cleaned_treatments_t <- pca_result_gastric_cleaned_treatments_t$x # Principal component scores (transformed data)
pca_variances_gastric_cleaned_treatments_t <- pca_result_gastric_cleaned_treatments_t$sdev^2  # Variance explained by each principal component
pca_proportions_gastric_cleaned_treatment_t <- pca_variances_gastric_cleaned_treatments_t / sum(pca_variances_gastric_cleaned_treatments_t)  # Proportion of variance explained by each principal component
pca_loadings_gastric_cleaned_treatments_t <- pca_result_gastric_cleaned_treatments_t$rotation  # Loadings (coefficients) of each variable on each principal component
plot(1:length(pca_variances_gastric_cleaned_treatments_t), pca_variances_gastric_cleaned_treatments_t, type = "b", xlab = "Principal Component", ylab = "Variance Explained",main = "Scree Plot")
plot(pca_values_gastric_cleaned_treatments_t[, 1], pca_values_gastric_cleaned_treatments_t[, 2], xlab = "PC1", ylab = "PC2", main = "PCA scatter plot for drug response of gastric cancer cell lines")
```

```{r}
library(ggplot2)
library(stats)
breast.cancer.celllines <- subset(prism.cl, lineage == "breast")
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
kidney.cancer.celllines <- subset(prism.cl, lineage == "kidney")
liver.cancer.celllines <- subset(prism.cl, lineage == "liver")
bone.cancer.celllines <- subset(prism.cl, lineage == "bone")

gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
breast.cancer.celllines.v <- breast.cancer.celllines $DepMap_ID
kidney.cancer.celllines.v <- kidney.cancer.celllines $DepMap_ID
bone.cancer.celllines.v <- bone.cancer.celllines $DepMap_ID
liver.cancer.celllines.v <- liver.cancer.celllines $DepMap_ID
cancer.celllines.v <- c(liver.cancer.celllines.v,bone.cancer.celllines.v,kidney.cancer.celllines.v,  breast.cancer.celllines.v,gastric.cancer.celllines.v)
prism.exp_celllines <- prism.exp[rownames(prism.exp) %in% cancer.celllines.v, ]

#Gastric cancer Dataframe of Prism.exp
G.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% gastric.cancer.celllines.v, ]
#Kidney cancer Dataframe of Prism.exp
K.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% kidney.cancer.celllines.v, ]
#Bone cancer Dataframe of Prism.exp
B.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% bone.cancer.celllines.v, ]
#Breast cancer Dataframe of Prism.exp
Br.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% breast.cancer.celllines.v, ]
#Liver cancer Dataframe of Prism.exp
L.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% liver.cancer.celllines.v, ]

# Transpose the dataframes
t.G.prism.exp <- t(G.prism.exp)
t.K.prism.exp<- t(K.prism.exp)
t.B.prism.exp<- t(B.prism.exp)
t.Br.prism.exp<-t(Br.prism.exp)
t.L.prism.exp<-t(L.prism.exp)

G.gene.exp_variances <- apply(t.G.prism.exp, MARGIN = 1, stats::var)
K.gene.exp_variances <- apply(t.K.prism.exp, MARGIN = 1, stats::var)
B.gene.exp_variances <- apply(t.B.prism.exp, MARGIN = 1, stats::var)
Br.gene.exp_variances <- apply(t.Br.prism.exp, MARGIN = 1, stats::var)
L.gene.exp_variances <- apply(t.L.prism.exp, MARGIN = 1, stats::var)

threshold <- 7
G.selected_genes_var <- t.G.prism.exp[G.gene.exp_variances > threshold, ]
threshold <- 7
K.selected_genes_var <- t.K.prism.exp[K.gene.exp_variances > threshold, ]
threshold2 <- 8
L.selected_genes_var <- t.L.prism.exp[L.gene.exp_variances > threshold2, ]
threshold <- 7
B.selected_genes_var <- t.B.prism.exp[B.gene.exp_variances > threshold, ]
threshold <- 7
Br.selected_genes_var <- t.Br.prism.exp[Br.gene.exp_variances > threshold, ]

G.prism.exp.var<-t(G.selected_genes_var)
K.prism.exp.var<-t(K.selected_genes_var)
L.prism.exp.var<-t(L.selected_genes_var)
B.prism.exp.var<-t(B.selected_genes_var)
Br.prism.exp.var<-t(Br.selected_genes_var)

G.column_names <- colnames(G.prism.exp.var)
K.column_names <- colnames(K.prism.exp.var)
L.column_names <- colnames(L.prism.exp.var)
B.column_names <- colnames(B.prism.exp.var)
Br.column_names <- colnames(Br.prism.exp.var)

genes_variance.V <- c(G.column_names,K.column_names,L.column_names,B.column_names,Br.column_names)
prism.exp_geneshv <- prism.exp_celllines[,colnames( prism.exp_celllines) %in% genes_variance.V ]

pca_result_prism.exp_geneshv <- prcomp(prism.exp_geneshv)
pca_values <- pca_result_prism.exp_geneshv $x # Principal component scores (transformed data)
pca_variances <- pca_result_prism.exp_geneshv $sdev^2  # Variance explained by each principal component
pca_proportions <- pca_variances / sum(pca_variances)  # Proportion of variance explained by each principal component
pca_loadings <- pca_result_prism.exp_geneshv $rotation  # Loadings (coefficients) of each variable on each principal component
 plot(1:length(pca_variances), pca_variances, type = "b", xlab = "Principal Component", ylab = "Variance Explained",
     main = "Scree Plot")
plot(pca_values[, 1], pca_values[, 2], xlab = "PC1", ylab = "PC2")


###
pca_data <- data.frame(PC1 = pca_values[, 1], PC2 = pca_values[, 2],CellLine = rownames(pca_values) )

bone.cancer.celllines.group<- "red"
kidney.cancer.celllines.group <- "blue"
liver.cancer.celllines.group <- "green"
gastric.cancer.celllines.group<- "purple"
breast.cancer.celllines.group <- "orange"

pca_data$Group <- NA
pca_data$Group[pca_data$CellLine %in% bone.cancer.celllines.v] <- "Bone cancer"
pca_data$Group[pca_data$CellLine %in% kidney.cancer.celllines.v] <- "Kidney cancer"
pca_data$Group[pca_data$CellLine %in% liver.cancer.celllines.v] <- "Liver cancer"
pca_data$Group[pca_data$CellLine %in% gastric.cancer.celllines.v] <- "Gastric cancer"
pca_data$Group[pca_data$CellLine %in% breast.cancer.celllines.v]<-"Breast cancer"

ggplot(pca_data, aes(x = PC1, y = PC2, color = Group)) +
  geom_point() +
  scale_color_manual(values = c("Bone cancer"=bone.cancer.celllines.group, "Kidney cancer"=kidney.cancer.celllines.group, "Liver cancer"=liver.cancer.celllines.group, "Gastric cancer"=gastric.cancer.celllines.group,"Breast cancer"= breast.cancer.celllines.group)) +
  labs(x = "PC1", y = "PC2", title = "PCA Scatter Plot for the gene expression of five different cancer subtypes")
```

```{r}
library(ggplot2)
library(ggforce)
library(cluster)
library(stats)
breast.cancer.celllines <- subset(prism.cl, lineage == "breast")
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
kidney.cancer.celllines <- subset(prism.cl, lineage == "kidney")
liver.cancer.celllines <- subset(prism.cl, lineage == "liver")
bone.cancer.celllines <- subset(prism.cl, lineage == "bone")

gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
breast.cancer.celllines.v <- breast.cancer.celllines $DepMap_ID
kidney.cancer.celllines.v <- kidney.cancer.celllines $DepMap_ID
bone.cancer.celllines.v <- bone.cancer.celllines $DepMap_ID
liver.cancer.celllines.v <- liver.cancer.celllines $DepMap_ID
cancer.celllines.v <- c(liver.cancer.celllines.v,bone.cancer.celllines.v,kidney.cancer.celllines.v,  breast.cancer.celllines.v,gastric.cancer.celllines.v)
prism.exp_celllines <- prism.exp[rownames(prism.exp) %in% cancer.celllines.v, ]

#Gastric cancer Dataframe of Prism.exp
G.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% gastric.cancer.celllines.v, ]
#Kidney cancer Dataframe of Prism.exp
K.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% kidney.cancer.celllines.v, ]
#Bone cancer Dataframe of Prism.exp
B.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% bone.cancer.celllines.v, ]
#Breast cancer Dataframe of Prism.exp
Br.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% breast.cancer.celllines.v, ]
#Liver cancer Dataframe of Prism.exp
L.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% liver.cancer.celllines.v, ]

# Transpose the dataframes
t.G.prism.exp <- t(G.prism.exp)
t.K.prism.exp<- t(K.prism.exp)
t.B.prism.exp<- t(B.prism.exp)
t.Br.prism.exp<-t(Br.prism.exp)
t.L.prism.exp<-t(L.prism.exp)

G.gene.exp_variances <- apply(t.G.prism.exp, MARGIN = 1, stats::var)
K.gene.exp_variances <- apply(t.K.prism.exp, MARGIN = 1, stats::var)
B.gene.exp_variances <- apply(t.B.prism.exp, MARGIN = 1, stats::var)
Br.gene.exp_variances <- apply(t.Br.prism.exp, MARGIN = 1, stats::var)
L.gene.exp_variances <- apply(t.L.prism.exp, MARGIN = 1, stats::var)

threshold <- 7
G.selected_genes_var <- t.G.prism.exp[G.gene.exp_variances > threshold, ]
threshold <- 7
K.selected_genes_var <- t.K.prism.exp[K.gene.exp_variances > threshold, ]
threshold2 <- 8
L.selected_genes_var <- t.L.prism.exp[L.gene.exp_variances > threshold2, ]
threshold <- 7
B.selected_genes_var <- t.B.prism.exp[B.gene.exp_variances > threshold, ]
threshold <- 7
Br.selected_genes_var <- t.Br.prism.exp[Br.gene.exp_variances > threshold, ]

G.prism.exp.var<-t(G.selected_genes_var)
K.prism.exp.var<-t(K.selected_genes_var)
L.prism.exp.var<-t(L.selected_genes_var)
B.prism.exp.var<-t(B.selected_genes_var)
Br.prism.exp.var<-t(Br.selected_genes_var)

G.column_names <- colnames(G.prism.exp.var)
K.column_names <- colnames(K.prism.exp.var)
L.column_names <- colnames(L.prism.exp.var)
B.column_names <- colnames(B.prism.exp.var)
Br.column_names <- colnames(Br.prism.exp.var)

genes_variance.V <- c(G.column_names,K.column_names,L.column_names,B.column_names,Br.column_names)
prism.exp_geneshv <- prism.exp_celllines[,colnames( prism.exp_celllines) %in% genes_variance.V ]

pca_result_prism.exp_geneshv <- prcomp(prism.exp_geneshv)
pca_values <- pca_result_prism.exp_geneshv $x # Principal component scores (transformed data)
pca_variances <- pca_result_prism.exp_geneshv $sdev^2  # Variance explained by each principal component
pca_proportions <- pca_variances / sum(pca_variances)  # Proportion of variance explained by each principal component
pca_loadings <- pca_result_prism.exp_geneshv $rotation  # Loadings (coefficients) of each variable on each principal component



###
pca_data <- data.frame(PC1 = pca_values[, 1], PC2 = pca_values[, 2],CellLine = rownames(pca_values) )

bone.cancer.celllines.group<- "red"
kidney.cancer.celllines.group <- "blue"
liver.cancer.celllines.group <- "green"
gastric.cancer.celllines.group<- "purple"
breast.cancer.celllines.group <- "orange"

pca_data$Group <- NA
pca_data$Group[pca_data$CellLine %in% bone.cancer.celllines.v] <- "Bone cancer"
pca_data$Group[pca_data$CellLine %in% kidney.cancer.celllines.v] <- "Kidney cancer"
pca_data$Group[pca_data$CellLine %in% liver.cancer.celllines.v] <- "Liver cancer"
pca_data$Group[pca_data$CellLine %in% gastric.cancer.celllines.v] <- "Gastric cancer"
pca_data$Group[pca_data$CellLine %in% breast.cancer.celllines.v]<-"Breast cancer"



# Perform PCA
pca_result <- prcomp(pca_data[, c("PC1", "PC2")])

# Extract the PC scores
pc_scores <- as.data.frame(pca_result_prism.exp_geneshv$x[, 1:2])
# Perform k-means clustering on the PC scores
kmeans_result <- kmeans(pc_scores[, c("PC1", "PC2")], centers = 5)

# Add cluster labels to the PC scores
pc_scores$cluster <- as.factor(kmeans_result$cluster)

# Calculate the center and radius of each cluster
cluster_centers <- aggregate(pc_scores[, c("PC1", "PC2")], list(cluster = pc_scores$cluster), mean)
cluster_radii <- aggregate(pc_scores[, c("PC1", "PC2")], list(cluster = pc_scores$cluster), function(x) max(dist(rbind(x, c(0, 0)))))

# Plot the clustered data with circles around each cluster
ggplot(pc_scores, aes(PC1, PC2, color = cluster)) +
  geom_point() +stat_ellipse(geom = "path", aes(group = cluster, color = cluster), alpha = 0.2)+
  labs(x = "PC1", y = "PC2", title = "PCA with K-means Clustering and Circles")
```
```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "HDAC1"
vector <- prism.cnv_gastric[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K56957086-001-06-3::0.00061034::HTS002"
vector0.00061034 <- prism_gastric[[column_name0]]
column_name1 <- "BRD-K56957086-001-06-3::0.0024414::HTS002"
vector0.0024414 <- prism_gastric[[column_name1]]
column_name2 <- "BRD-K56957086-001-06-3::0.00976562::HTS002"
vector0.00976562 <- prism_gastric[[column_name2]]
column_name3<- "BRD-K56957086-001-06-3::0.0390625::HTS002"
vector0.0390625 <- prism_gastric[[column_name3]]
column_name4 <- "BRD-K56957086-001-06-3::0.15625::HTS002"
vector0.15625 <- prism_gastric[[column_name4]]
column_name5 <- "BRD-K56957086-001-06-3::0.625::HTS002"
vector0.625 <- prism_gastric[[column_name5]]
column_name6 <- "BRD-K56957086-001-06-3::2.5::HTS002"
vector2.5 <- prism_gastric[[column_name6]]
column_name7 <- "BRD-K56957086-001-06-3::10::HTS002"
vector10<- prism_gastric[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector0.00061034, vector0.0024414, vector0.00976562 , vector0.0390625, vector0.15625,vector0.625, vector2.5 , vector10)
par(mar = c(5, 5, 4, 7))
# Plot the vectors
matplot(vector, vectors, type = "p", pch = 16, col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"),
        xlab = " CNVs of HDAC1", ylab = "BRD-K56957086-001-06-3")
# Get the coordinates for the legend
legend_x <- 1.2 # Adjust the value as needed
legend_y <- 0.5
# Add a legend
legend(legend_x, legend_y, legend = c("0.00061034", "0.0024414", "0.00976562", "0.0390625", "0.15625", "0.625", "2.5", "10"),
       col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"), pch = 16,xpd = TRUE, bty = "n")
```

```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.exp_gastric <- prism.exp[rownames(prism.exp) %in% gastric.cancer.celllines.v, ]

# Get the common row names
common_rows <- intersect(row.names(prism_gastric), row.names(prism.exp_gastric)) 

# Create new dataframes with common rows
new_prism.exp.gaaa <- prism.exp_gastric[common_rows, ]
new_prismgaaa <- prism_gastric[common_rows, ]
# Select a column by its name and store it in a vector
column_name <- "HDAC1"
vector <- new_prism.exp.gaaa[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K56957086-001-06-3::0.00061034::HTS002"
vector1 <- new_prismgaaa[[column_name0]]
column_name1 <- "BRD-K56957086-001-06-3::0.0024414::HTS002"
vector2 <- new_prismgaaa[[column_name1]]
column_name2 <- "BRD-K56957086-001-06-3::0.00976562::HTS002"
vector3 <- new_prismgaaa[[column_name2]]

column_name4 <- "BRD-K56957086-001-06-3::0.15625::HTS002"
vector5 <- new_prismgaaa[[column_name4]]
column_name5 <- "BRD-K56957086-001-06-3::0.625::HTS002"
vector6 <- new_prismgaaa[[column_name5]]
column_name6 <- "BRD-K56957086-001-06-3::2.5::HTS002"
vector7 <- new_prismgaaa[[column_name6]]
column_name7 <- "BRD-K56957086-001-06-3::10::HTS002"
vector8<- new_prismgaaa[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector1, vector2, vector3,  vector5,vector6, vector7, vector8)
par(mar = c(5, 5, 4, 7))
# Plot the vectors
matplot(vector, vectors, type = "p", pch = 16, col = c("blue", "red", "green",  "purple", "pink", "brown", "black"),
        xlab = "TPM values of HDAC1", ylab = "BRD-K56957086-001-06-3")
# Get the coordinates for the legend
legend_x <- 9.11  # Adjust the value as needed
legend_y <- 0.5
# Add a legend
legend(legend_x, legend_y, legend = c("0.00061034", "0.0024414", "0.00976562", "0.0390625", "0.15625", "0.625", "2.5", "10"),
       col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"), pch = 16,xpd = TRUE, bty = "n")
```
```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "BCR"
vector <- prism.cnv_gastric[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K35329391-334-01-7::0.00061034::HTS002"
vector1 <- prism_gastric[[column_name0]]
column_name1 <- "BRD-K35329391-334-01-7::0.0024414::HTS002"
vector2 <- prism_gastric[[column_name1]]
column_name2 <- "BRD-K35329391-334-01-7::0.00976562::HTS002"
vector3 <- prism_gastric[[column_name2]]
column_name3<- "BRD-K35329391-334-01-7::0.0390625::HTS002"
vector4 <- prism_gastric[[column_name3]]
column_name4 <- "BRD-K35329391-334-01-7::0.15625::HTS002"
vector5 <- prism_gastric[[column_name4]]
column_name5 <- "BRD-K35329391-334-01-7::0.625::HTS002"
vector6 <- prism_gastric[[column_name5]]
column_name6 <- "BRD-K35329391-334-01-7::2.5::HTS002"
vector7 <- prism_gastric[[column_name6]]
column_name7 <- "BRD-K35329391-334-01-7::10::HTS002"
vector8<- prism_gastric[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector1, vector2, vector3, vector4, vector5,vector6, vector7, vector8)
par(mar = c(5, 5, 4, 7))
# Plot the vectors
matplot(vector, vectors, type = "p", pch = 16, col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"),
        xlab = "CNVs of BCR", ylab = "BRD-K35329391-334-01-7")
# Get the coordinates for the legend
legend_x <- 1.31  # Adjust the value as needed
legend_y <- 0.5
# Add a legend
legend(legend_x, legend_y, legend = c("0.00061034", "0.0024414", "0.00976562", "0.0390625", "0.15625", "0.625", "2.5", "10"),
       col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"), pch = 16,xpd = TRUE, bty = "n")
```

```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.exp_gastric <- prism.exp[rownames(prism.exp) %in% gastric.cancer.celllines.v, ]

# Get the common row names
common_rows <- intersect(row.names(prism_gastric), row.names(prism.exp_gastric)) 

# Create new dataframes with common rows
new_prism.exp.gaaa <- prism.exp_gastric[common_rows, ]
new_prismgaaa <- prism_gastric[common_rows, ]
# Select a column by its name and store it in a vector
column_name <- "BCR"
vector <- new_prism.exp.gaaa[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K35329391-334-01-7::0.00061034::HTS002"
vector1 <- new_prismgaaa[[column_name0]]
column_name1 <- "BRD-K35329391-334-01-7::0.0024414::HTS002"
vector2 <- new_prismgaaa[[column_name1]]
column_name2 <- "BRD-K35329391-334-01-7::0.00976562::HTS002"
vector3 <- new_prismgaaa[[column_name2]]
column_name3<- "BRD-K35329391-334-01-7::0.0390625::HTS002"
vector4 <- new_prismgaaa[[column_name3]]
column_name4 <- "BRD-K35329391-334-01-7::0.15625::HTS002"
vector5 <- new_prismgaaa[[column_name4]]
column_name5 <- "BRD-K35329391-334-01-7::0.625::HTS002"
vector6 <- new_prismgaaa[[column_name5]]
column_name6 <- "BRD-K35329391-334-01-7::2.5::HTS002"
vector7 <- new_prismgaaa[[column_name6]]
column_name7 <- "BRD-K35329391-334-01-7::10::HTS002"
vector8<- new_prismgaaa[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector1, vector2, vector3, vector4, vector5,vector6, vector7, vector8)
par(mar = c(5, 5, 4, 7))
# Plot the vectors
matplot(vector, vectors, type = "p", pch = 16, col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"),
        xlab = "TPM values of BCR", ylab = "BRD-K35329391-334-01-7")
# Get the coordinates for the legend
legend_x <- 5.6  # Adjust the value as needed
legend_y <- 0.5
# Add a legend
legend(legend_x, legend_y, legend = c("0.00061034", "0.0024414", "0.00976562", "0.0390625", "0.15625", "0.625", "2.5", "10"),
       col = c("blue", "red", "green", "orange", "purple", "pink", "brown", "black"), pch = 16,xpd = TRUE, bty = "n")
```

```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "BCR"
vector50 <- prism.cnv_gastric[[column_name]]
# Select a column by its name and store it in a vector
column_name <- "BRD-K35329391-334-01-7::10::HTS002"
vector51 <- prism_gastric[[column_name]]
library(ggplot2)

# Create a data frame with the variables
data <- data.frame(KDR = vector50, 
                   HTS002 = vector51)

# Create the scatter plot using ggplot2
ggplot(data, aes(x = KDR, y = HTS002)) +
  geom_point(size = 3, color = "blue") +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  labs(x = "B-cell Domain Receptor (BCR) Expression Level", 
       y = "BRD-K35329391-334-01-7::10::HTS002",
       title = "Prediction model of BRD-K35329391-334-01-7::10::HTS002 based on CNVs of BCR") +
  theme_minimal()


```
```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "HDAC1"
vector200 <- prism.cnv_gastric[[column_name]]
# Select a column by its name and store it in a vector
column_name <- "BRD-K56957086-001-06-3::10::HTS002"
vector201 <-prism_gastric[[column_name]]
# Create a data frame with the variables
data <- data.frame(KDR = vector200, 
                   HTS002 = vector201)

# Create the scatter plot using ggplot2
ggplot(data, aes(x = KDR, y = HTS002)) +
  geom_point(size = 3, color = "blue") +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  labs(x = "HDAC1 Expression Level", 
       y = "BRD-K56957086-001-06-3::10::HTS002",
       title = "Scatter Plot of HDAC1 vs BRD-K56957086-001-06-3::10::HTS002") +
  theme_minimal()
```

Supplements:


```{r}
library(ggplot2)
library(stats)
breast.cancer.celllines <- subset(prism.cl, lineage == "breast")
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
kidney.cancer.celllines <- subset(prism.cl, lineage == "kidney")
liver.cancer.celllines <- subset(prism.cl, lineage == "liver")
bone.cancer.celllines <- subset(prism.cl, lineage == "bone")

gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
breast.cancer.celllines.v <- breast.cancer.celllines $DepMap_ID
kidney.cancer.celllines.v <- kidney.cancer.celllines $DepMap_ID
bone.cancer.celllines.v <- bone.cancer.celllines $DepMap_ID
liver.cancer.celllines.v <- liver.cancer.celllines $DepMap_ID
cancer.celllines.v <- c(liver.cancer.celllines.v,bone.cancer.celllines.v,kidney.cancer.celllines.v,  breast.cancer.celllines.v,gastric.cancer.celllines.v)
prism.exp_celllines <- prism.exp[rownames(prism.exp) %in% cancer.celllines.v, ]

#Gastric cancer Dataframe of Prism.exp
G.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% gastric.cancer.celllines.v, ]
#Kidney cancer Dataframe of Prism.exp
K.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% kidney.cancer.celllines.v, ]
#Bone cancer Dataframe of Prism.exp
B.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% bone.cancer.celllines.v, ]
#Breast cancer Dataframe of Prism.exp
Br.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% breast.cancer.celllines.v, ]
#Liver cancer Dataframe of Prism.exp
L.prism.exp<-prism.exp_celllines[rownames(prism.exp_celllines) %in% liver.cancer.celllines.v, ]

# Transpose the dataframes
t.G.prism.exp <- t(G.prism.exp)
t.K.prism.exp<- t(K.prism.exp)
t.B.prism.exp<- t(B.prism.exp)
t.Br.prism.exp<-t(Br.prism.exp)
t.L.prism.exp<-t(L.prism.exp)

G.gene.exp_variances <- apply(t.G.prism.exp, MARGIN = 1, stats::var)
K.gene.exp_variances <- apply(t.K.prism.exp, MARGIN = 1, stats::var)
B.gene.exp_variances <- apply(t.B.prism.exp, MARGIN = 1, stats::var)
Br.gene.exp_variances <- apply(t.Br.prism.exp, MARGIN = 1, stats::var)
L.gene.exp_variances <- apply(t.L.prism.exp, MARGIN = 1, stats::var)

threshold <- 7
G.selected_genes_var <- t.G.prism.exp[G.gene.exp_variances > threshold, ]
threshold <- 7
K.selected_genes_var <- t.K.prism.exp[K.gene.exp_variances > threshold, ]
threshold2 <- 8
L.selected_genes_var <- t.L.prism.exp[L.gene.exp_variances > threshold2, ]
threshold <- 7
B.selected_genes_var <- t.B.prism.exp[B.gene.exp_variances > threshold, ]
threshold <- 7
Br.selected_genes_var <- t.Br.prism.exp[Br.gene.exp_variances > threshold, ]

G.prism.exp.var<-t(G.selected_genes_var)
K.prism.exp.var<-t(K.selected_genes_var)
L.prism.exp.var<-t(L.selected_genes_var)
B.prism.exp.var<-t(B.selected_genes_var)
Br.prism.exp.var<-t(Br.selected_genes_var)

G.column_names <- colnames(G.prism.exp.var)
K.column_names <- colnames(K.prism.exp.var)
L.column_names <- colnames(L.prism.exp.var)
B.column_names <- colnames(B.prism.exp.var)
Br.column_names <- colnames(Br.prism.exp.var)

genes_variance.V <- c(G.column_names,K.column_names,L.column_names,B.column_names,Br.column_names)
prism.exp_geneshv <- prism.exp_celllines[,colnames( prism.exp_celllines) %in% genes_variance.V ]

pca_result_prism.exp_geneshv <- prcomp(prism.exp_geneshv)
pca_values <- pca_result_prism.exp_geneshv $x # Principal component scores (transformed data)
pca_variances <- pca_result_prism.exp_geneshv $sdev^2  # Variance explained by each principal component
pca_proportions <- pca_variances / sum(pca_variances)  # Proportion of variance explained by each principal component
pca_loadings <- pca_result_prism.exp_geneshv $rotation  # Loadings (coefficients) of each variable on each principal component
 


###
pca_data <- data.frame(PC1 = pca_values[, 1], PC2 = pca_values[, 2],CellLine = rownames(pca_values) )

bone.cancer.celllines.group<- "red"
kidney.cancer.celllines.group <- "blue"
liver.cancer.celllines.group <- "green"
gastric.cancer.celllines.group<- "purple"
breast.cancer.celllines.group <- "orange"

pca_data$Group <- NA
pca_data$Group[pca_data$CellLine %in% bone.cancer.celllines.v] <- "Bone cancer"
pca_data$Group[pca_data$CellLine %in% kidney.cancer.celllines.v] <- "Kidney cancer"
pca_data$Group[pca_data$CellLine %in% liver.cancer.celllines.v] <- "Liver cancer"
pca_data$Group[pca_data$CellLine %in% gastric.cancer.celllines.v] <- "Gastric cancer"
pca_data$Group[pca_data$CellLine %in% breast.cancer.celllines.v]<-"Breast cancer"

library(cluster)
library(factoextra)


fviz_nbclust(pc_scores, kmeans, method = "wss") + geom_vline(xintercept = 3, linetype=2)

library(purrr)
library(factoextra)
library(cluster)
#higher values indicates a better clustering
avg_sil <- function(k) {
  km.res <- kmeans(pc_scores, centers = 5, nstart = 25)
  ss <- silhouette(km.res$cluster, dist(pc_scores))
  mean(ss[, 3])
  }
#compute and plot wss for k=2 to k=15
k.values <- 2:15

# extract avg silhouette for 2-15 clusters
avg_sil_values <- map_dbl(k.values, avg_sil)


#computing with silhouette method
fviz_nbclust(pc_scores, kmeans, method = "silhouette")

pam.res4 <- pam(pc_scores, 3,  metric = "euclidean", stand = FALSE)
fviz_cluster(pam.res4, data = pc_scores, palette = c("#FC4E07", "#00AFBB", "#E7B800","#4C8C33","green"), ellipse.type = "euclid", 
star.plot = TRUE, 
repel = TRUE, 
ggtheme = theme_minimal(), geom = "point" )
fviz_silhouette(pam.res4, palette = "jco", ggtheme = theme_classic())

```
```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "HDAC1"
vector <- prism.cnv_gastric[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K56957086-001-06-3::0.00061034::HTS002"
vector0.00061034 <- prism_gastric[[column_name0]]
column_name1 <- "BRD-K56957086-001-06-3::0.0024414::HTS002"
vector0.0024414 <- prism_gastric[[column_name1]]
column_name2 <- "BRD-K56957086-001-06-3::0.00976562::HTS002"
vector0.00976562 <- prism_gastric[[column_name2]]
column_name3<- "BRD-K56957086-001-06-3::0.0390625::HTS002"
vector0.0390625 <- prism_gastric[[column_name3]]
column_name4 <- "BRD-K56957086-001-06-3::0.15625::HTS002"
vector0.15625 <- prism_gastric[[column_name4]]
column_name5 <- "BRD-K56957086-001-06-3::0.625::HTS002"
vector0.625 <- prism_gastric[[column_name5]]
column_name6 <- "BRD-K56957086-001-06-3::2.5::HTS002"
vector2.5 <- prism_gastric[[column_name6]]
column_name7 <- "BRD-K56957086-001-06-3::10::HTS002"
vector10<- prism_gastric[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector0.00061034, vector0.0024414, vector0.00976562 , vector0.0390625, vector0.15625,vector0.625, vector2.5 , vector10)
par(mar = c(5, 5, 4, 7))
correlationnn<-cor(vector, vectors)
# Create a bar plot of correlations
conc<-data.frame("0.00061", "0.00244", "0.00976", "0.03906", "0.15625", "0.625", "2.5", "10")

barplot(correlationnn, beside = TRUE, names.arg = colnames(conc), 
        xlab = "Dosage of BRD-K56957086-001-06-3 '", ylab = "Correlation of drug response and CNVs of HDAC1", cex.names = 0.4)
```

```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.exp_gastric <- prism.exp[rownames(prism.exp) %in% gastric.cancer.celllines.v, ]

# Get the common row names
common_rows <- intersect(row.names(prism_gastric), row.names(prism.exp_gastric)) 

# Create new dataframes with common rows
new_prism.exp.gaaa <- prism.exp_gastric[common_rows, ]
new_prismgaaa <- prism_gastric[common_rows, ]
# Select a column by its name and store it in a vector
column_name <- "HDAC1"
vector <- new_prism.exp.gaaa[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K56957086-001-06-3::0.00061034::HTS002"
vector1 <- new_prismgaaa[[column_name0]]
column_name1 <- "BRD-K56957086-001-06-3::0.0024414::HTS002"
vector2 <- new_prismgaaa[[column_name1]]
column_name2 <- "BRD-K56957086-001-06-3::0.00976562::HTS002"
vector3 <- new_prismgaaa[[column_name2]]

column_name4 <- "BRD-K56957086-001-06-3::0.15625::HTS002"
vector5 <- new_prismgaaa[[column_name4]]
column_name5 <- "BRD-K56957086-001-06-3::0.625::HTS002"
vector6 <- new_prismgaaa[[column_name5]]
column_name6 <- "BRD-K56957086-001-06-3::2.5::HTS002"
vector7 <- new_prismgaaa[[column_name6]]
column_name7 <- "BRD-K56957086-001-06-3::10::HTS002"
vector8<- new_prismgaaa[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector1, vector2, vector3,  vector5,vector6, vector7, vector8)
par(mar = c(5, 5, 4, 7))
correlationnn<-cor(vector, vectors)
# Create a bar plot of correlations
conc<-data.frame("0.00061", "0.00244", "0.00976",  "0.15625", "0.625", "2.5", "10")

barplot(correlationnn, beside = TRUE, names.arg = colnames(conc), 
        xlab = "Dosage of BRD-K56957086-001-06-3 '", ylab = "Correlation of drug response and expression of HDAC1", cex.names = 0.4)
```
```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "BCR"
vector <- prism.cnv_gastric[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K35329391-334-01-7::0.00061034::HTS002"
vector1 <- prism_gastric[[column_name0]]
column_name1 <- "BRD-K35329391-334-01-7::0.0024414::HTS002"
vector2 <- prism_gastric[[column_name1]]
column_name2 <- "BRD-K35329391-334-01-7::0.00976562::HTS002"
vector3 <- prism_gastric[[column_name2]]
column_name3<- "BRD-K35329391-334-01-7::0.0390625::HTS002"
vector4 <- prism_gastric[[column_name3]]
column_name4 <- "BRD-K35329391-334-01-7::0.15625::HTS002"
vector5 <- prism_gastric[[column_name4]]
column_name5 <- "BRD-K35329391-334-01-7::0.625::HTS002"
vector6 <- prism_gastric[[column_name5]]
column_name6 <- "BRD-K35329391-334-01-7::2.5::HTS002"
vector7 <- prism_gastric[[column_name6]]
column_name7 <- "BRD-K35329391-334-01-7::10::HTS002"
vector8<- prism_gastric[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector1, vector2, vector3, vector4, vector5,vector6, vector7, vector8)
par(mar = c(5, 5, 4, 7))
correlationnn<-cor(vector, vectors)
# Create a bar plot of correlations
conc<-data.frame("0.00061", "0.00244", "0.00976", "0.03906", "0.15625", "0.625", "2.5", "10")

barplot(correlationnn, beside = TRUE, names.arg = colnames(conc), 
        xlab = "Dosage of BRD-K35329391-334-01-7 '", ylab = "Correlation of drug response and CNVs of BCR", cex.names = 0.4)

```
```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.exp_gastric <- prism.exp[rownames(prism.exp) %in% gastric.cancer.celllines.v, ]

# Get the common row names
common_rows <- intersect(row.names(prism_gastric), row.names(prism.exp_gastric)) 

# Create new dataframes with common rows
new_prism.exp.gaaa <- prism.exp_gastric[common_rows, ]
new_prismgaaa <- prism_gastric[common_rows, ]
# Select a column by its name and store it in a vector
column_name <- "BCR"
vector <- new_prism.exp.gaaa[[column_name]]
# Select a column by its name and store it in a vector
column_name0 <- "BRD-K35329391-334-01-7::0.00061034::HTS002"
vector1 <- new_prismgaaa[[column_name0]]
column_name1 <- "BRD-K35329391-334-01-7::0.0024414::HTS002"
vector2 <- new_prismgaaa[[column_name1]]
column_name2 <- "BRD-K35329391-334-01-7::0.00976562::HTS002"
vector3 <- new_prismgaaa[[column_name2]]
column_name3<- "BRD-K35329391-334-01-7::0.0390625::HTS002"
vector4 <- new_prismgaaa[[column_name3]]
column_name4 <- "BRD-K35329391-334-01-7::0.15625::HTS002"
vector5 <- new_prismgaaa[[column_name4]]
column_name5 <- "BRD-K35329391-334-01-7::0.625::HTS002"
vector6 <- new_prismgaaa[[column_name5]]
column_name6 <- "BRD-K35329391-334-01-7::2.5::HTS002"
vector7 <- new_prismgaaa[[column_name6]]
column_name7 <- "BRD-K35329391-334-01-7::10::HTS002"
vector8<- new_prismgaaa[[column_name7]]
# Create a matrix of vectors
vectors <- cbind(vector1, vector2, vector3, vector4, vector5,vector6, vector7, vector8)
par(mar = c(5, 5, 4, 7))
correlationnn<-cor(vector, vectors)
# Create a bar plot of correlations
conc<-data.frame("0.00061", "0.00244", "0.00976", "0.03906", "0.15625", "0.625", "2.5", "10")

barplot(correlationnn, beside = TRUE, names.arg = colnames(conc), 
        xlab = "Dosage of BRD-K35329391-334-01-7 '", ylab = "Correlation of drug response and expression of BCR", cex.names = 0.4)
```

```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "BCR"
vector110 <- prism.cnv[[column_name]]
# Select a column by its name and store it in a vector
column_name <- "BRD-K35329391-334-01-7::10::HTS002"
vector111 <- new_df[[column_name]]
# Create a data frame with the variables
data <- data.frame(BCR = vector110, 
                   HTS002 = vector111)

# Create the scatter plot using ggplot2
ggplot(data, aes(x = BCR, y = HTS002)) +
  geom_point(size = 3, color = "blue") +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  labs(x = "B-cell Domain Receptor (BCR) Expression Level", 
       y = "BRD-K35329391-334-01-7::10::HTS002",
       title = "Prediction model of BRD-K35329391-334-01-7::10::HTS002 based on CNVs of BCR") +
  theme_minimal()
```

```{r}
gastric.cancer.celllines <- subset(prism.cl, lineage == "gastric")
gastric.cancer.celllines.v <- gastric.cancer.celllines $DepMap_ID
prism_gastric <- prism[rownames(prism) %in% gastric.cancer.celllines.v, ]
prism.cnv_gastric <- prism.cnv[rownames(prism.cnv) %in% gastric.cancer.celllines.v, ]
# Select a column by its name and store it in a vector
column_name <- "HDAC1"
vector330 <- prism.cnv[[column_name]]
# Select a column by its name and store it in a vector
column_name <- "BRD-K56957086-001-06-3::10::HTS002"
vector331 <- new_df[[column_name]]
# Create a data frame with the variables
data <- data.frame(KDR = vector330, 
                   HTS002 = vector331)

# Create the scatter plot using ggplot2
ggplot(data, aes(x = KDR, y = HTS002)) +
  geom_point(size = 3, color = "blue") +
  geom_smooth(method = "lm", color = "red", se = FALSE) +
  labs(x = "HDAC1 Expression Level", 
       y = "BRD-K56957086-001-06-3::10::HTS002",
       title = "Scatter Plot of HDAC1 vs BRD-K56957086-001-06-3::10::HTS002") +
  theme_minimal()
```

